name: Aprilandpaul
favicon: null
layout_spectrum: 0.96027
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d9d9d9'
    - '#473c2a'
    - '#8e8d88'
    - '#8d5645'
  brandStrength: 0.6210168849211186
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
